# Generated by Django 3.0.5 on 2020-04-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvP', '0002_auto_20200409_0324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
