# Generated by Django 3.0.5 on 2020-04-14 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvP', '0003_auto_20200409_0329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('school_name', models.CharField(max_length=250)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
